[tool.pylint.'MESSAGES CONTROL']

disable = [
    "missing-docstring",
    "invalid-name",
    "too-few-public-methods",
    "too-many-public-methods",
    "fixme",
    "redefined-builtin",
    "redefined-outer-name",
    "too-many-return-statements",
    "import-error",
    "too-many-branches",
    "too-many-arguments",
    "too-many-instance-attributes",
    "no-member",
]
