name: "Run Tests"
on: [push, pull_request, workflow_dispatch]

jobs:
  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        include:
          - python-version: "3.6"
          - python-version: "3.7"
          - python-version: "3.8"
          - python-version: "3.9"
          - python-version: "3.10"

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: |
          python -m pip install -U pip

      - name: Configure environments
        run: |
          python --version

      - name: Setup neovim
        run: |
          NVIM_VERSION="latest"
          NVIM_DOWNLOAD_URL="https://github.com/neovim/neovim/releases/latest/download/nvim.appimage"
          if [[ "${{ matrix.python-version}}" == "3.6" ]]; then
            NVIM_VERSION="v0.6.1"
            NVIM_DOWNLOAD_URL="https://github.com/neovim/neovim/releases/download/$NVIM_VERSION/nvim.appimage"
          fi

          mkdir -p $HOME/.local/bin
          wget -O $HOME/.local/bin/nvim $NVIM_DOWNLOAD_URL
          chmod +x $HOME/.local/bin/nvim
          pip install pynvim
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check neovim version
        run: |
          nvim --version

      - name: Install dependencies
        run: |
          pip install pytest codecov pytest-cov
          pip install pyproject-flake8

      - name: Linting
        run: |
          pflake8 semshi/
          # pylint semshi/

      - name: Run tests
        run: |
          pytest -v --cov semshi/ --cov-report term-missing:skip-covered --ignore test/test_fuzz.py test/

      - name: Test coverage
        run: codecov

